# write python program to get input eight numbers from user and display the unique numbers (once)
s=set()

n=input("enter the number : ")
s.add(int(n))
n=input("enter the number : ")
s.add(int(n))
n=input("enter the number : ")
s.add(int(n))
n=input("enter the number : ")
s.add(int(n))
n=input("enter the number : ")
s.add(int(n))
n=input("enter the number : ")
s.add(int(n))
n=input("enter the number : ")
s.add(int(n))
n=input("enter the number : ")
s.add(int(n))

print(s)